### ISSUE TITLE
[ADD] 사전과제 - 이미지 동적으로 불러오기

### ISSUE THREAD

**Issue by Guel-git** [Guel-git/Wanted-Pre-Onboarding#3]
### Background
웹에서 이미지를 동적으로 불러오고,
일정 시간이 지나면 원래 상태로 돌아가는 기능을 구현합니다.

### TODO
- [ ] 웹에 있는 이미지 5개를 동적으로 긁어오기 (URL > UIImage)
- [ ] CollectionView cellForItemAt 메소드에 Button action 추가하기
(button을 누를 때마다 클로저를 통해 indexPath.item을 전달하는)
- [ ] VC 로 전달된 item 에 해당되는 imageList 의 image 변경해주기
- [ ] 1초 가량 지우면 다시 system에 있는 "photo" 로 변경해주는 타이머 추가하기
